import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footers from "./Components/Footers";
import Spinner from "./Components/Spinner";
import { CartProvider } from "./context/CartContext";


export const metadata = {
  title: "E Commerce Website",
  description: "Generated by create next app",
};




const inter = Inter({ subsets: ["latin"] });


export default function RootLayout({ children }) {




  return (

    <CartProvider>
    <html lang="en">


      <body className={inter.className} suppressHydrationWarning={true}>



        {/* Render Navbar only if it's not an admin route */}

        {/* <Spinner/> */}


        <Navbar />


        {/* {loading ? <Spinner/>: children} */}

        {children}



        {/* Render Footer only if it's not an admin route */}
        <div>

          <Footers />
        </div>




      </body>

    </html>
    </CartProvider>
  );
}
